/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  aux_sym_section_name_token1 = 2,
  anon_sym_RBRACK = 3,
  anon_sym_EQ = 4,
  sym_setting_name = 5,
  aux_sym_setting_value_cont_token1 = 6,
  sym_setting_text = 7,
  sym_setting_text_cont = 8,
  aux_sym_comment_token1 = 9,
  aux_sym_comment_token2 = 10,
  sym__eol = 11,
  sym__space = 12,
  sym_document = 13,
  sym_unnamed_section = 14,
  sym_section = 15,
  sym_section_name = 16,
  sym_setting = 17,
  sym_setting_value = 18,
  sym_setting_value_cont = 19,
  sym_comment = 20,
  aux_sym_document_repeat1 = 21,
  aux_sym_unnamed_section_repeat1 = 22,
  aux_sym_setting_value_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [aux_sym_section_name_token1] = "text",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_setting_name] = "setting_name",
  [aux_sym_setting_value_cont_token1] = "setting_value_cont_token1",
  [sym_setting_text] = "text",
  [sym_setting_text_cont] = "text",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "text",
  [sym__eol] = "_eol",
  [sym__space] = "_space",
  [sym_document] = "document",
  [sym_unnamed_section] = "unnamed_section",
  [sym_section] = "section",
  [sym_section_name] = "section_name",
  [sym_setting] = "setting",
  [sym_setting_value] = "setting_value",
  [sym_setting_value_cont] = "setting_value_cont",
  [sym_comment] = "comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_unnamed_section_repeat1] = "unnamed_section_repeat1",
  [aux_sym_setting_value_repeat1] = "setting_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_section_name_token1] = aux_sym_section_name_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_setting_name] = sym_setting_name,
  [aux_sym_setting_value_cont_token1] = aux_sym_setting_value_cont_token1,
  [sym_setting_text] = aux_sym_section_name_token1,
  [sym_setting_text_cont] = aux_sym_section_name_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_section_name_token1,
  [sym__eol] = sym__eol,
  [sym__space] = sym__space,
  [sym_document] = sym_document,
  [sym_unnamed_section] = sym_unnamed_section,
  [sym_section] = sym_section,
  [sym_section_name] = sym_section_name,
  [sym_setting] = sym_setting,
  [sym_setting_value] = sym_setting_value,
  [sym_setting_value_cont] = sym_setting_value_cont,
  [sym_comment] = sym_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_unnamed_section_repeat1] = aux_sym_unnamed_section_repeat1,
  [aux_sym_setting_value_repeat1] = aux_sym_setting_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_name_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_setting_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_setting_value_cont_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_setting_text] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_text_cont] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_unnamed_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_value] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_value_cont] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unnamed_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setting_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 29,
        '\r', 1,
        '=', 21,
        '[', 18,
        '\\', 7,
        ']', 20,
        '\t', 30,
        ' ', 30,
        '#', 26,
        ';', 26,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(24);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_section_name_token1);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_setting_name);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_setting_value_cont_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_setting_text);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_setting_text_cont);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {(TSStateId)(-1),},
  [32] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_setting_name] = ACTIONS(1),
    [aux_sym_setting_value_cont_token1] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [sym__eol] = ACTIONS(5),
    [sym__space] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_document] = STATE(22),
    [sym_unnamed_section] = STATE(5),
    [sym_section] = STATE(19),
    [sym_section_name] = STATE(7),
    [sym_setting] = STATE(11),
    [sym_comment] = STATE(1),
    [aux_sym_document_repeat1] = STATE(6),
    [aux_sym_unnamed_section_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_setting_name] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [sym__eol] = ACTIONS(5),
    [sym__space] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_comment,
    STATE(7), 1,
      sym_section_name,
    STATE(9), 1,
      aux_sym_document_repeat1,
    STATE(19), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [26] = 9,
    ACTIONS(15), 1,
      aux_sym_setting_value_cont_token1,
    ACTIONS(17), 1,
      sym_setting_text,
    ACTIONS(19), 1,
      aux_sym_comment_token1,
    ACTIONS(21), 1,
      sym__eol,
    ACTIONS(23), 1,
      sym__space,
    STATE(3), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_setting_value_repeat1,
    STATE(26), 1,
      sym_setting_value_cont,
    STATE(30), 1,
      sym_setting_value,
  [54] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_setting_name,
    STATE(4), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_unnamed_section_repeat1,
    STATE(11), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [78] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_document_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(7), 1,
      sym_section_name,
    STATE(19), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [104] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      sym_section_name,
    STATE(9), 1,
      aux_sym_document_repeat1,
    STATE(19), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [130] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_setting_name,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_unnamed_section_repeat1,
    STATE(11), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [154] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_setting_name,
    STATE(8), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_unnamed_section_repeat1,
    STATE(11), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [178] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_section_name,
    STATE(19), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    STATE(9), 2,
      sym_comment,
      aux_sym_document_repeat1,
  [202] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(40), 1,
      sym_setting_name,
    STATE(11), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(10), 2,
      sym_comment,
      aux_sym_unnamed_section_repeat1,
  [224] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(11), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(43), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [240] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(15), 1,
      aux_sym_setting_value_cont_token1,
    ACTIONS(45), 1,
      sym__eol,
    STATE(12), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_setting_value_repeat1,
    STATE(26), 1,
      sym_setting_value_cont,
  [262] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(13), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(47), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [278] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(14), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [294] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(15), 1,
      aux_sym_setting_value_cont_token1,
    ACTIONS(45), 1,
      sym__eol,
    STATE(15), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_setting_value_repeat1,
    STATE(26), 1,
      sym_setting_value_cont,
  [316] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(15), 1,
      aux_sym_setting_value_cont_token1,
    ACTIONS(51), 1,
      sym__eol,
    STATE(16), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_setting_value_repeat1,
    STATE(26), 1,
      sym_setting_value_cont,
  [338] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(17), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [354] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(55), 1,
      aux_sym_setting_value_cont_token1,
    ACTIONS(58), 1,
      sym__eol,
    STATE(26), 1,
      sym_setting_value_cont,
    STATE(18), 2,
      sym_comment,
      aux_sym_setting_value_repeat1,
  [374] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(19), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [389] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      sym__space,
    ACTIONS(64), 1,
      sym_setting_text_cont,
    STATE(20), 1,
      sym_comment,
    ACTIONS(62), 2,
      aux_sym_setting_value_cont_token1,
      sym__eol,
  [406] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      anon_sym_EQ,
    STATE(21), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [420] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [434] = 4,
    ACTIONS(19), 1,
      aux_sym_comment_token1,
    ACTIONS(70), 1,
      aux_sym_section_name_token1,
    STATE(23), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [448] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(72), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [462] = 5,
    ACTIONS(19), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      sym__space,
    ACTIONS(74), 1,
      aux_sym_comment_token2,
    ACTIONS(76), 1,
      sym__eol,
    STATE(25), 1,
      sym_comment,
  [478] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    STATE(26), 1,
      sym_comment,
    ACTIONS(78), 2,
      aux_sym_setting_value_cont_token1,
      sym__eol,
  [492] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    STATE(27), 1,
      sym_comment,
    ACTIONS(80), 2,
      aux_sym_setting_value_cont_token1,
      sym__eol,
  [506] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(82), 1,
      sym__eol,
    STATE(28), 1,
      sym_comment,
  [519] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(84), 1,
      sym__eol,
    STATE(29), 1,
      sym_comment,
  [532] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(86), 1,
      sym__eol,
    STATE(30), 1,
      sym_comment,
  [545] = 1,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
  [549] = 1,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 104,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 154,
  [SMALL_STATE(9)] = 178,
  [SMALL_STATE(10)] = 202,
  [SMALL_STATE(11)] = 224,
  [SMALL_STATE(12)] = 240,
  [SMALL_STATE(13)] = 262,
  [SMALL_STATE(14)] = 278,
  [SMALL_STATE(15)] = 294,
  [SMALL_STATE(16)] = 316,
  [SMALL_STATE(17)] = 338,
  [SMALL_STATE(18)] = 354,
  [SMALL_STATE(19)] = 374,
  [SMALL_STATE(20)] = 389,
  [SMALL_STATE(21)] = 406,
  [SMALL_STATE(22)] = 420,
  [SMALL_STATE(23)] = 434,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 462,
  [SMALL_STATE(26)] = 478,
  [SMALL_STATE(27)] = 492,
  [SMALL_STATE(28)] = 506,
  [SMALL_STATE(29)] = 519,
  [SMALL_STATE(30)] = 532,
  [SMALL_STATE(31)] = 545,
  [SMALL_STATE(32)] = 549,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unnamed_section, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unnamed_section_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unnamed_section_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unnamed_section_repeat1, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_value, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_value, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 4, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_value_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_value_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_value_cont, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_value_repeat1, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_value_cont, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ini(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ini",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 4,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
